// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWHGy1a0tZhoZh_uvqSr14mQ8p0ta7Bts',
    appId: '1:277952387396:web:52d9c883a0289883a59f11',
    messagingSenderId: '277952387396',
    projectId: 'mynotes-flutter-project-thebao',
    authDomain: 'mynotes-flutter-project-thebao.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-thebao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD441-IZmTChjYfuWx-rAIAANkUGxjJJvc',
    appId: '1:277952387396:android:ec8cab8b81301b64a59f11',
    messagingSenderId: '277952387396',
    projectId: 'mynotes-flutter-project-thebao',
    storageBucket: 'mynotes-flutter-project-thebao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWkSqCJl8IZ3Nxdwdz0uA08phtuT1gyk',
    appId: '1:277952387396:ios:57e5ba00a181d9d4a59f11',
    messagingSenderId: '277952387396',
    projectId: 'mynotes-flutter-project-thebao',
    storageBucket: 'mynotes-flutter-project-thebao.appspot.com',
    iosBundleId: 'vn.hellovietname.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbWkSqCJl8IZ3Nxdwdz0uA08phtuT1gyk',
    appId: '1:277952387396:ios:63e56ff5afcc87e4a59f11',
    messagingSenderId: '277952387396',
    projectId: 'mynotes-flutter-project-thebao',
    storageBucket: 'mynotes-flutter-project-thebao.appspot.com',
    iosBundleId: 'vn.hellovietname.mynotes.RunnerTests',
  );
}
